// VueWithApi/VueWithApi/ClientApp/src/components/auth/SignOut.vue
﻿<template>
    <div>
        <h2>Sign Out Page</h2>
        <p>{{message}}</p>
    </div>
</template>

<script>
    import Vue from 'vue';
    import api from '../../api';

    export default {
        data: function () {
            return {
                message: 'Signing out...',
            };
        },
        beforeMount: function () {
            api.signOut().then(data => {
                this.$store.dispatch('initialize').then(() => {
                    this.message = "You have been signed out";
                }).catch(() => {
                    this.message = "You have been signed out but some data was not cleared. Please close your browser tab.";
                });
            }).catch(err => {
                this.message = "Sign out failed";
            });
        }
    };
</script>

<style lang="scss">
</style>

// VueWithApi/VueWithApi/ClientApp_React/src/components/signout/SignOut.tsx
import React, { useEffect, useState } from "react";
import api from "../../api/api";
import { useStore } from "../../store";

export function SignOut() {
  const [message, setMessage] = useState<string>('Signing out...');
  const store = useStore();

  const signOut = function () {
    api
      .signOut()
      .then(() => {
        store
          .initialize()
          .then(() => {
            setMessage("You have been signed out");
          })
          .catch(() => {
            setMessage(
              "You have been signed out but some data was not cleared. Please close your browser tab.",
            );
          });
      })
      .catch(() => {
        setMessage("Sign out failed");
      });
  };

  useEffect(() => {
    signOut();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);

  return (
    <div>
      <h2>Sign Out Page</h2>
      <p>{ message }</p>
    </div>
  );
}
