// VueWithApi/VueWithApi/ClientApp_React/src/components/forgotPassword/ForgotPassword.tsx
import { useState, useMemo, useEffect, useRef } from "react";
import api from "../../api/api";

export const ForgotPassword = () => {
  const [message, setMessage] = useState<string>("");
  const [email, setEmail] = useState<string>("");
  const [emailError, setEmailError] = useState<string>("");

  const submitForm = (evt: React.FormEvent<HTMLFormElement>) => {
    evt.preventDefault();
    setMessage("Please wait...");
    api
      .sendPasswordResetMessage(email, "/")
      .then((data) => {
        setMessage(data.message ? data.message : "Success");
      })
      .catch((error) => {
        setMessage(error.message ? error.message : "Something went wrong");
      });
  };


  const emailEl = useRef<HTMLInputElement>(null);
  
  useEffect(() => {
    emailEl.current.focus();
  }, []);

  const emailIsValid = useMemo<boolean>(() => {
    if (email.length === 0) {
      return false;
    }
    var testEl = document.createElement("input");
    testEl.type = "email";
    testEl.value = email;
    return testEl.checkValidity();
  }, [email]);

  return (
    <div className="focusBox">
      <h2>Forgot Password</h2>
      <div className="forgotPassword">
        <form className="form" onSubmit={submitForm}>
          <div className="field field-stacked form_row">
            <label className="field_label" htmlFor="email">
              Email
            </label>
            <input
              className="field_element field_element-fullWidth register_email"
              id="email"
              ref={emailEl}
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              type="text"
              placeholder="you@example.com"
            />
            {emailError && (
              <span v-if="emailError" className="field_error">
                {emailError}
              </span>
            )}
          </div>

          <div className="field form_row">
            <button
              disabled={!emailIsValid}
              type="submit"
              className="field_element field_element-fullWidth field_element-tall forgotPassword_button"
            >
              Get Password Reset Link
            </button>
          </div>
          {message && (
            <div className="message message-notice register_message">
              {message}
            </div>
          )}
        </form>
      </div>
    </div>
  );
};

// ClientAppVue/src/components/auth/ForgotPassword.vue
﻿<template>
    <div class="focusBox">
        <h2>Forgot Password</h2>
        <div class="forgotPassword">
            <form @submit.prevent="submitForm" class="form">
                <div class="field field-stacked form_row">
                    <label class="field_label" for="email">Email</label>
                    <input class="field_element field_element-fullWidth register_email"
                           ref="email"
                           id="email"
                           v-model="email"
                           type="text"
                           placeholder="you@example.com">
                    <span v-if="emailError" class="field_error">{{emailError}}</span>
                </div>

                <div class="field form_row">
                    <button :disabled="!emailIsValid"
                            type="submit"
                            class="field_element field_element-fullWidth field_element-tall forgotPassword_button">
                        Get Password Reset Link
                    </button>
                </div>
                <div class="message message-notice register_message" v-if="message">
                    {{message}}
                </div>
            </form>
        </div>
    </div>
</template>

<script>
    import Vue from 'vue';
    import api from '../../api';

    export default {
        data: function () {
            return {
                email: '',
                emailError: '',
                message: ''
            };
        },
        computed: {
            emailIsValid: function () {
                if (this.email.length == 0) {
                    return false;
                }
                var testEl = document.createElement('input');
                testEl.type = 'email';
                testEl.value = this.email;
                return testEl.checkValidity();
            }
        },
        methods: {
            submitForm: function () {
                this.message = "Please wait...";
                api.sendPasswordResetMessage(this.email, '/')
                    .then(data => {
                        this.message = data.message ? data.message : 'Success';
                    })
                    .catch(error => {
                        this.message = error.message ? error.message : 'Something went wrong';
                    });
            }
        },
        mounted: function () {
            this.$nextTick(() => {
                this.$refs.email.focus();
            });
        }
    };
</script>

<style lang="scss">
</style>
