// VueWithApi/VueWithApi/ClientApp/src/components/signin/SignIn.tsx
import React, { useState } from "react";
import api from "../../api/api";
import { Link } from "react-router-dom";

export function SignIn() {
  const [usernameError, setusernameError] = useState("");
  const [passwordError, setpasswordError] = useState("");
  const [message, setMessage] = useState("");
  const [savedUsernames, setSavedUsernames] = useState([]);
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [trustThisDevice, setTrustThisDevice] = useState<boolean>(false);
  const [signInEnabled, setSignInEnabled] = useState<boolean>(true);
  const [signInType, setSignInType] = useState<string>('');
  const [nextUrl, setNextUrl] = useState<string>('');
  const [idPrefix, setIdPrefix] = useState<string>(''); //todo this is a prop is original code.
  const submitForm = function (evt:React.FormEvent<HTMLFormElement>): void {
      evt.preventDefault();
    setMessage("Please wait...");
    if (password.length > 0) {
        signIn();
    }
    else {
        getOneTimeCode();
    }
}

const showSavedUsernames = function() {
    return savedUsernames.length && username.length === 0;
}

const getId = function(name) {
    let prefix = '';
    if (typeof idPrefix === 'string') {
        prefix = idPrefix + '-';
    }
    return prefix + name;
}

const getOneTimeCode = function () {
    api.sendOneTimeCode(username, nextUrl)
        .then(data => {
            setMessage('We sent sent a one time code to your email');
                this.$refs.password.focus();
        })
        .catch(error => {
            if (error.message) {
                setMessage(error.message);
            }
            else {
                setMessage('Something went wrong');
            }
        });
}

const signIn = function () {
    if (signInEnabled) {
        let oneTimeCode = password.replace(' ', '');
        if (signInType === 'code' || /^[0-9]{6}$/.test(oneTimeCode)) {
            api.authenticateOneTimeCode(username, oneTimeCode, trustThisDevice)
                .then(data => signInDone(data))
                .catch(error => signInFailed(error));
        }
        else {
            api.authenticatePassword(username, password, trustThisDevice, nextUrl)
                .then(data => signInDone(data))
                .catch(error => signInFailed(error));
        }
    }
}

const signInDone = function (data) {
    saveUsernames();
    this.$store.dispatch('initialize').then(() => {
        if (typeof data.nextUrl === 'string') {
            this.$router.push(data.nextUrl);
        }
    });
}
const signInFailed = function (error) {
    console.log(error);
    if (typeof error.response.status !== 'undefined' && error.response.status === 401) {
        setPassword('');
    }
        setMessage(error.message ? error.message : 'Something went wrong')
}

function saveUsernames() {
    if (trustThisDevice) {
        let usernames = savedUsernames.filter(name => name.toLowerCase() !== username.toLowerCase());
        if (username.length <= 100) {
            usernames.unshift(username);
        }
        this.$cookie.set('SavedUsernames', usernames.slice(0, 3).join(' '), { expires: '1Y' });
    }
}

function clearSavedUsernames() {
    this.$cookie.delete('SavedUsernames');
    setSavedUsernames([]);
}


  return (
    <div className="focusBox">
      <h2>Sign In</h2>
      <form className="form" onSubmit={submitForm}>
        <section className="field field-stacked form_row">
          <label className="field_label" htmlFor={getId('username')}>Email</label>
          <input
            className="field_element field_element-fullWidth signIn_username"
            value={username}
            type="text"
            placeholder="you@example.com"
            onChange={e=> setUsername(e.target.value)}
          ></input>
          {usernameError && (
            <span className="field_error">{usernameError}</span>
          )}
        </section>

        {showSavedUsernames && (
        <section>
          <div className="field field-stacked form_row">
            <label className="field_label" htmlFor={getId('password')}>Password or one time code</label>
            <input
              className="field_element field_element-fullWidth signIn_password"
              id={getId('password')}
              type="password"
              placeholder="****** / 123..."
              value={password}
              onChange={e=> setPassword(e.target.value)}
            />
            {passwordError && (
              <span className="field_error">{passwordError}</span>
            )}
          </div>

          <div className="field field-checkbox form_row">
            <input
              className="field_element"
              type="checkbox"
              checked={trustThisDevice}
              onChange={e=> setTrustThisDevice(e.target.checked)}
            />
            <label className="field_label">Trust this device</label>
          </div>

          <div className="fields fields-flexSpaceBetween form_row">
            <div className="field">
              <button
                className="field_element field_element-tall signIn_signInButton"
                type="submit"
              >
                Sign in
              </button>
            </div>
            <div className="field">
              <button className="field_element field_element-tall signIn_oneTimeCodeButton">
                Get one time code
              </button>
            </div>
          </div>
          {message && (
          <div className="message message-notice signIn_message">
            {message}
          </div>
          )}
        </section>
        )}
        <div className="minorNav signIn_footer">
          <Link className="signIn_forgotPasswordLink" to="/forgotpassword">
            Forgot password?
          </Link>
        </div>
      </form>
      {showSavedUsernames && (
      <section className="savedUsernames">
        <header className="savedUsernames_header">
          <span className="savedUsernames_title">Saved Usernames</span>
        </header>
        <div className="form">
          {savedUsernames.map((username, index) => {
            return (
              <div className="field form_row">
                <button className="savedUsernames_username field_element field_element-fullWidth field_element-tall">
                  {username}
                </button>
              </div>
            );
          })}
        </div>
        <div className="savedUsernames_footer">
          <a href="#" className="savedUsernames_clearUsernames">
            Clear saved usernames
          </a>
        </div>
      </section>
      )}
    </div>
  );
}

// VueWithApi/VueWithApi/ClientApp/src/components/auth/SignIn.vue
﻿<template>
    <div class="focusBox">
        <h2>Sign In</h2>
        <div class="signIn">
            <form @submit.prevent="submitForm" class="form">
                <section class="field field-stacked form_row">
                    <label class="field_label" :for="getId('username')">Email</label>
                    <input class="field_element field_element-fullWidth signIn_username"
                           ref="username"
                           :id="getId('username')"
                           v-model="username"
                           type="text"
                           placeholder="you@example.com">
                    <span v-if="usernameError" class="field_error">{{usernameError}}</span>
                </section>
                <section v-show="!showSavedUsernames">
                    <div class="field field-stacked form_row">
                        <label class="field_label" :for="getId('password')">Password or one time code</label>
                        <input class="field_element field_element-fullWidth signIn_password"
                               ref="password"
                               type="password"
                               :id="getId('password')"
                               placeholder="****** / 123..."
                               v-model="password">
                        <span v-if="passwordError" class="field_error">{{passwordError}}</span>
                    </div>

                    <div class="field field-checkbox form_row">
                        <input class="field_element"
                               type="checkbox"
                               :id="getId('stay-signed-in')"
                               v-model="trustThisDevice">
                        <label class="field_label" :for="getId('stay-signed-in')">Trust this device</label>
                    </div>

                    <div class="fields fields-flexSpaceBetween form_row">
                        <div class="field">
                            <button class="field_element field_element-tall signIn_signInButton"
                                    type="submit"
                                    :disabled="!signInEnabled">
                                Sign in
                            </button>
                        </div>
                        <div class="field">
                            <button class="field_element field_element-tall signIn_oneTimeCodeButton"
                                    :type="password.length == 0 ? 'submit' : 'button'"
                                    :disabled="username.length == 0 || password.length > 0">
                                Get one time code
                            </button>
                        </div>
                    </div>
                    <div class="message message-notice signIn_message" v-if="message">
                        {{message}}
                    </div>
                </section>
                <div class="minorNav signIn_footer">
                    <router-link class="signIn_forgotPasswordLink" to="/forgotpassword">Forgot password?</router-link>
                </div>
            </form>
            <section class="savedUsernames" v-if="showSavedUsernames">
                <header class="savedUsernames_header">
                    <span class="savedUsernames_title">Saved Usernames</span>
                </header>
                <div class="form">
                    <div class="field form_row" v-for="name in savedUsernames" v-bind:key="name">
                        <button @click="selectUsername(name)"
                                class="savedUsernames_username field_element field_element-fullWidth field_element-tall">
                            {{name}}
                        </button>
                    </div>
                </div>
                <div class="savedUsernames_footer">
                    <a href="#" class="savedUsernames_clearUsernames" @click.prevent="clearSavedUsernames">Clear saved usernames</a>
                </div>
            </section>
        </div>
    </div>
</template>

<script>
    import Vue from 'vue';
    import api from '../../api';

    var VueCookie = require('vue-cookie');

    Vue.use(VueCookie);

    export default {
        props: {
            nextUrl: String,
            loginHint: String,
            idPrefix: String,
        },
        data: function () {
            return {
                savedUsernames: [],
                username: '',
                password: '',
                passwordError: '',
                message: '',
                trustThisDevice: true
            };
        },
        watch: {
            username: function (newUsername, oldUsername) {
                this.message = '';
                if (newUsername.length == 0) {
                    this.password = '';
                    this.loadSavedUsernames();
                }
            },
            password: function () {
                this.message = '';
            }
        },
        computed: {
            showSavedUsernames: function () {
                return this.savedUsernames.length && this.username.length == 0;
            },
            usernameError: function () {
                if (this.username.length == 0) {
                    return '';
                }
                if (this.username.includes(' ')) {
                    return 'No spaces allowed'
                }
                return '';
            },
            usernameIsValid: function () {
                return this.username.length > 0 && !this.usernameError;
            },
            signInEnabled: function () {
                return this.usernameIsValid && this.password.length > 0;
            },
        },
        methods: {
            getId: function (name) {
                let prefix = '';
                if (typeof this.idPrefix === 'string') {
                    prefix = this.idPrefix + '-';
                }
                return prefix + name;
            },
            selectUsername: function (name) {
                this.username = name;
                this.$nextTick(() => {
                    this.$refs.password.focus();
                });
            },
            submitForm: function () {
                this.message = "Please wait...";
                if (this.password.length > 0) {
                    this.signIn();
                }
                else {
                    this.getOneTimeCode();
                }
            },
            getOneTimeCode: function () {
                api.sendOneTimeCode(this.username, this.nextUrl)
                    .then(data => {
                        this.message = 'We sent sent a one time code to your email';
                        this.$nextTick(() => {
                            this.$refs.password.focus();
                        });
                    })
                    .catch(error => {
                        if (error.message) {
                            this.message = error.message;
                        }
                        else {
                            this.message = 'Something went wrong';
                        }
                    });
            },
            signIn: function () {
                if (this.signInEnabled) {
                    let oneTimeCode = this.password.replace(' ', '');
                    if (this.signInType == 'code' || /^[0-9]{6}$/.test(oneTimeCode)) {
                        api.authenticateOneTimeCode(this.username, oneTimeCode, this.trustThisDevice)
                            .then(data => this.signInDone(data))
                            .catch(error => this.signInFailed(error));
                    }
                    else {
                        api.authenticatePassword(this.username, this.password, this.trustThisDevice, this.nextUrl)
                            .then(data => this.signInDone(data))
                            .catch(error => this.signInFailed(error));
                    }
                }
            },
            signInDone: function (data) {
                this.saveUsernames();
                this.$store.dispatch('initialize').then(() => {
                    if (typeof data.nextUrl === 'string') {
                        this.$router.push(data.nextUrl);
                    }
                });
            },
            signInFailed: function (error) {
                console.log(error);
                if (typeof error.response.status !== 'undefined' && error.response.status == 401) {
                    this.password = '';
                }
                this.$nextTick(() => {
                    this.message = error.message ? error.message : 'Something went wrong';
                });
            },
            loadSavedUsernames() {
                this.savedUsernames = [];
                const usernames = this.$cookie.get('SavedUsernames');
                if (typeof usernames == 'string') {
                    let count = 0;
                    usernames.split(' ').forEach(name => {
                        count++;
                        if (count <= 3 && name.length > 1 && name.length <= 100) {
                            this.savedUsernames.push(name);
                        }
                    });
                }
            },
            saveUsernames() {
                if (this.trustThisDevice) {
                    let usernames = this.savedUsernames.filter(name => name.toLowerCase() !== this.username.toLowerCase());
                    if (this.username.length <= 100) {
                        usernames.unshift(this.username);
                    }
                    this.$cookie.set('SavedUsernames', usernames.slice(0, 3).join(' '), { expires: '1Y' });
                }
            },
            clearSavedUsernames() {
                this.$cookie.delete('SavedUsernames');
                this.savedUsernames = [];
            }
        },
        mounted: function () {
            this.loadSavedUsernames();
            if (this.loginHint) {
                this.username = this.loginHint;
                this.$nextTick(() => {
                    this.$refs.password.focus();
                });
            }
            else {
                this.$nextTick(() => {
                    this.$refs.username.focus();
                });
            }
        }
    };
</script>

<style lang="scss">
</style>
