// VueWithApi/VueWithApi/ClientApp/src/components/home/Home.tsx
import React, { useState, useEffect } from "react";
import api from "../../api/api";
export function Home() {
  const [message, setMessage] = useState("");

  useEffect(() => {
    async function fetchData() {
      api
        .tryToGetProtectedInfoButDontRedirectIfUnauthenticated()
        .then((data) => {
          setMessage(data);
        })
        .catch((err) => {
          if (
            typeof err.response.status !== "undefined" &&
            err.response.status === 401
          ) {
            setMessage("Please sign in to see the message.");
          } else {
            setMessage(err.message ? err.message : "An error occurred");
          }
        });
    }
    fetchData();
  }, []);

  return (
    <div>
      <h1>Home</h1>
      <div>Protected Message: {message}</div>
    </div>
  );
}

// ClientAppVue/src/components/app/Home.vue
﻿<template>
    <div>
        <h2>Home</h2>
        <div>
            Protected Message: {{message}}
        </div>
    </div>
</template>

<script>
    import Vue from 'vue';
    import api from '../../api';

    export default Vue.extend({
        data() {
            return {
                message: '',
            };
        },
        beforeMount() {
            api.tryToGetProtectedInfoButDontRedirectIfUnauthenticated().then(data => {
                this.message = data.message;
            }).catch(err => {
                if (typeof (err.response.status) !== 'undefined' && err.response.status == 401) {
                    this.message = 'Please sign in to see the message.';
                }
                else {
                    this.message = err.message ? err.message : 'An error occurred';
                }
            });
        }
    });
</script>

<style lang="scss">
    
</style>
