// VueWithApi/VueWithApi/ClientApp_React/src/components/setpassword/SetPassword.tsx
import { useState } from "react";
import { Link, useHistory } from "react-router-dom";
import api from "../../api/api";

export const SetPassword = () => {
  const [message, setMessage] = useState<string>("");
  const [newPassword, setNewPassword] = useState<string>("");
  const [confirmPassword, setConfirmPassword] = useState<string>("");
  let history = useHistory();

  const minimumPasswordLength = 1; //todo get from config.

  const setPassword = (
    event: React.MouseEvent<HTMLButtonElement, MouseEvent>,
  ) => {
    if (newPassword !== confirmPassword) {
      setMessage("Passwords do not match");
    } else if (newPassword.length < minimumPasswordLength) {
      setMessage(
        "Password must be at least " +
          minimumPasswordLength +
          " characters long",
      );
    } else {
      api
        .setPassword(newPassword)
        .then((data) => {
          history.push(data.nextUrl ? data.nextUrl : "/");
        })
        .catch((err) => {
          setMessage(err.message);
        });
    }
  };

  return (
    <div className="focusBox">
      <h2>Set New Password</h2>
      <div className="setPassword">
        <div className="form_row field field-stacked">
          <label className="field_label">New Password</label>
          <input
            value={newPassword}
            onChange={(e) => setNewPassword(e.target.value)}
            type="password"
            className="field_element field_element-fullWidth"
          />
          {/* <PasswordStrengthMeter :minStrengthInBits="minimumPasswordStrength" :password="newPassword"></PasswordStrengthMeter> */}
        </div>
        <div className="form_row field field-stacked">
          <label className="field_label">Repeat New Password</label>
          <input
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            type="password"
            className="field_element field_element-fullWidth"
          />
        </div>
        <div className="form_row field">
          <button
            className="field_element field_element-fullWidth field_element-tall setPassword_button"
            disabled={!newPassword}
            onClick={setPassword}
          >
            Set Password
          </button>
        </div>
        <div className="form_row field">
          <Link to="/myaccount">Cancel</Link>
        </div>
        {message && <div className="notification">{message}</div>}
      </div>
    </div>
  );
};

// VueWithApi/VueWithApi/ClientApp/src/components/account/SetPassword.vue
﻿<template>
    <div class="focusBox">
        <h2>Set New Password</h2>
        <div class="setPassword">
            <div class="form_row field field-stacked">
                <label class="field_label">New Password</label>
                <input v-model="newPassword" type="password" class="field_element field_element-fullWidth" />
                <PasswordStrengthMeter :minStrengthInBits="minimumPasswordStrength" :password="newPassword"></PasswordStrengthMeter>
            </div>
            <div class="form_row field field-stacked">
                <label class="field_label">Repeat New Password</label>
                <input v-model="confirmPassword" type="password" class="field_element field_element-fullWidth" />
            </div>
            <div class="form_row field">
                <button :disable="!newPassword" @click="setPassword" class="field_element field_element-fullWidth field_element-tall setPassword_button">Set Password</button>
            </div>
            <div class="form_row field">
                <router-link to="/myaccount">Cancel</router-link>
            </div>
            <div v-if="message" class="notification">
                {{message}}
            </div>
        </div>
    </div>
</template>

<script>
    import Vue from 'vue';
    import { mapGetters } from 'vuex';
    import api from '../../api';
    import PasswordStrengthMeter from './PasswordStrengthMeter.vue';

    export default Vue.extend({
        data() {
            return {
                newPassword: '',
                confirmPassword: '',
                message: ''
            };
        },
        computed: {
            ...mapGetters([
                'minimumPasswordStrength',
                'minimumPasswordLength',
            ]),
        },
        watch: {
            newPassword: function (val) {
                this.message = '';
            },
            confirmPassword: function (val) {
                this.message = '';
            }
        },
        methods: {
            setPassword() {
                if (this.newPassword !== this.confirmPassword) {
                    this.message = 'Passwords do not match';
                }
                else if (this.newPassword.length < this.minimumPasswordLength) {
                    this.message = 'Password must be at least ' + this.minimumPasswordLength + ' characters long';
                }
                else {
                    api.setPassword(this.newPassword).then(data => {
                        this.$router.push(data.nextUrl ? data.nextUrl : '/');
                    }).catch(err => {
                        this.message = err.message;
                    });
                }
            }
        },
        components: {
            PasswordStrengthMeter
        }
    });
</script>

<style lang="scss">
</style>
