// VueWithApi/VueWithApi/ClientApp_React/src/App.tsx
import React from "react";
import { useEffect } from "react";
import "./App.css";
import { BrowserRouter as Router, Link } from "react-router-dom";
import { useStore } from "./store";
import { Routes } from "./Routes";

function App():JSX.Element {
  const store = useStore();
  const user = useStore((state) => state.user);
  const isSignedIn = useStore((state) => state.signedIn());

  useEffect(() => {
    store.initialize();
  }, []);

  return (
    <div className="App" id="app">
      <h1>SimpleIAM Passwordless Example</h1>
      <Router>
        <div className="menu">
          <Link to="/">Home</Link>

          {/* need to secure perm: canViewProfile*/}
          {isSignedIn && <Link to="/myaccount">My Account</Link>}

          {!isSignedIn && (
            <>
              <Link to="/signin">Sign In</Link>
              <Link to="/register">Register</Link>
            </>
          )}

          {isSignedIn && <Link to="/signout">Sign out</Link>}
        </div>
        <Routes />
      </Router>
      <div className="debug">
      Signed in: {isSignedIn ? "yes" : "no"} <br />
      <pre>User: {JSON.stringify(user)} </pre>
      </div>

    </div>
  );
}

export default App;

// VueWithApi/VueWithApi/ClientApp/src/components/app/App.vue
﻿<template>
    <div v-if="initializationFailed">
        Initialization failed
    </div>
    <div v-else-if="!initialized">
        Loading...
    </div>
    <div v-else id="app" class="app">
        <h1>SimpleIAM Passwordless Example</h1>
        <div class="menu">
            <router-link to="/">Home</router-link>
            <router-link v-if="canViewProfile" to="/myaccount">My Account</router-link>
            <router-link v-if="!signedIn" to="/signin">Sign In</router-link>
            <router-link v-if="!signedIn" to="/register">Register</router-link>
            <router-link v-if="signedIn" to="/signout">Sign Out</router-link>
        </div>
        <router-view></router-view>
    </div>
</template>

<script>
    import Vue from 'vue';
    import { mapGetters } from 'vuex';

    export default Vue.extend({
        data() {
            return {
            };
        },
        computed: {
            ...mapGetters([
                'initializationFailed',
                'initialized',
                'canViewProfile',
                'signedIn'
            ])
        },
    });
</script>

<style lang="scss">
@import '../../assets/css/site.css';

    .app {
        max-width: 900px;
        margin: 0 auto;
    }
    .menu {
        display: flex;
    }
    .menu a {
        margin: 10px;       
    }
</style>
